### ISSUE TITLE
Accepting pull requests?

### ISSUE THREAD

**Issue by BlaineMoore** [ryansechrest/github-updater-demo#1]
Hello,

I like how your plugin updater works, but see some room for improvements. I'll be updating my fork to work the way that I want it to, and was wondering if you are interested in pull requests for this particular projects for the improvements and/or changes I am making? Not sure since this seems more like an example project/demo and not sure if you plan to work with it anymore in the future.

If you don't mind receiving pull requests, would you rather have small individual pull requests with the various changes? If so I can segment and implement one at a time. (I just don't want to seem rude if I drop 3 or 4 pull requests in short order without asking you first.)

Some of the changes I am working on adding:
- `Tested Up To` header in the plugin is checked for to avoid having to explicitly call it elsewhere in the plugin (already implemented)
- Checking releases rather than the direct files in the branch on the repository
- Displaying information about the plugin update using the WordPress popup rather than loading a separate changelog HTML page (and feeding that information from the releases)

**Comment by ryansechrest** [comment]
Hi Blaine,

I'm definitely open to checking out your improvements and incorporating them if they make sense. I appreciate you wanting to contribute and asking before creating pull requests.

I have a few clarifying questions I'd like to ask, so if you create an issue for each of your three enhancements, I'll ask them in each respective issue.

**Comment by BlaineMoore** [comment]
Created separate issues for each feature as requested and closing this one, thanks!
