### ISSUE TITLE
Feature: Check Releases Rather Than Raw Branch For New Versions of the Plugin

### ISSUE THREAD

**Issue by BlaineMoore** [ryansechrest/github-updater-demo#3]
The current version of your class checks the raw version of a plugin, which means that as soon as a commit is made to a plugin that version is then available for automatic updates (assuming of course that you update the version number.) For better control over what is actually sent to the WordPress sites, you could create a specific `Production` branch that is only for the latest version, but isn't quite as elegant a solution as I'd prefer for my own use.

What I will be implementing is rather than checking the raw files in a branch, is to check releases. This way, I can create a definitive changelog of versions without maintaining a separate website or unrelated files for the plugin in the individual releases that would work for both public and private repositories, as well as pre-release versions that individual plugins could opt-in to (such as on `staging` sites) for testing.

For example, [here's the releases page for my fork of your demo](https://github.com/BlaineMoore/github-updater-demo/releases/), which currently only has the release as you've created it but I'll add a new version with my updates as I go along. The Tag could be accessed as the version number, the description could be shown in the changelog for the latest version as a minimum viable updat with the plugin link going to the changelog, or even be parsed from the API to create a full changelog in the popup (which I'll also be implementing for my version and will list as Issue #4 ). 

Here is the API link for my fork, with only 1 release now but would list all releases in reverse chronological order once there are more, and which would work with both public and private repos: https://api.github.com/repos/BlaineMoore/github-updater-demo/releases

(I have not implemented this yet but will be my next project.)

**Comment by ryansechrest** [comment]
Hello! I did consider using releases, but ultimately figured that `master` is usually the production branch. This allows someone to use `master` and `develop`, if they want to keep things simple, or use releases, since everything would ultimately get merged into `master` anyway. I didn't want to overcomplicate GitHubUpdater by forcing the use of releases or supporting multiple ways of doing things.

**Comment by BlaineMoore** [comment]
Fair enough. I'm still going to update my fork because it works better for my use case. That'll be my next project, probably. :)

**Comment by ryansechrest** [comment]
Good luck! I'll poke my head in here and there to see how it turns out!
